[delivery]
mode='preserve-modules'
entry_names='entry/[name]-[hash:12].[ext]'
chunk_names='chunks/[name]-[index]-[hash:12].[ext]'
module_names='modules/[path]-[hash:12].[ext]'
preload='entry'
[optimization]
preset='maximum'
[objective]
codecs='raw'
[effort]
level=13
