[javascript]
priority = "size-first"
local_name_reserve = 48
candidate_search = "off"

[mangle]
identifiers = true
properties = true
pool_strings = true
exports = false
extern_fields = true

[objective]
codecs = "brotli"

[effort]
level = 15
