[optimization]
preset = "none"

[javascript]
optimization_level = 0
candidate_search = "off"
strip_console = false

[mangle]
identifiers = false
properties = false
exports = false
pool_strings = false

[bundle]
mode = "single"
