[optimization]
preset = "maximum"
inlining = false
scalar_replacement = true

[javascript]
priority = "size-first"
strip_debug = false
strip_console_calls = false

[mangle]
identifiers = true
properties = true

[objective]
codecs = "raw"

[effort]
level = 13

[policy.tactics]
inlining='off'
