
[decisions]
read="/home/azureuser/lilscript/benchmarks/migration-results/2026-10-01-q2-decisions/artifacts/independent-bodies-128/raw.choices.lock"
[optimization]
preset='maximum'
[objective]
codecs='raw'
[effort]
level=13
