[optimization]
preset='maximum'
inlining=false
constant_folding=false
scalar_replacement=false
[javascript]
priority='size-first'
ecmascript='es2021'
strip_debug=false
strip_console_calls=false
[objective]
codecs='brotli'
[effort]
level=14
[policy.tactics]
string-pooling='off'
helper-sharing='off'
call-specialization='off'
