effort.level=0
objective.codecs="raw"
[language]
absence="unified"
[target.native]
objective="balanced"
cycle_collection_threshold=1
[host.native]
argumentCount="host_lil_arg_count"
argument="host_lil_arg"
environment="host_lil_env"
output="host_lil_stdout"
errorOutput="host_lil_stderr"
readInput="host_lil_stdin"
readText="host_lil_read_text"
writeText="host_lil_write_text"
wallTime="host_lil_wall_time"
cpuTime="host_lil_cpu_time"
exitProcess="host_lil_exit"
