[optimization]
preset='maximum'
inlining=false
scalar_replacement=false
[javascript]
priority='size-first'
strip_debug=false
strip_console_calls=false
assume_pristine_builtins=false
[objective]
codecs='raw'
[effort]
level=13
[policy.tactics]
property-mangling='on'
