[javascript]
priority = "size-first"
function_spelling = "arrow"
aggregate_layout = "named"

[mangle]
identifiers = true
properties = true
pool_strings = true

[objective]
codecs = "brotli"

[effort]
level = 15
